### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by llaumgui** [davesteele/gnome-gmail#8]
Hi,

On Fedora 22, is there a [bug report of crash on launch](https://bugzilla.redhat.com/show_bug.cgi?id=1268672):
~~~
gnome-gmail
Traceback (most recent call last):
  File "/usr/share/gnome-gmail/gnomegmail.py", line 43, in <module>
    from gi.repository import Wnck
  File "/usr/lib64/python2.7/site-packages/gi/importer.py", line 158, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib64/python2.7/site-packages/gi/module.py", line 271, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib64/python2.7/site-packages/gi/module.py", line 120, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded
~~~

Have you an idea ?

thx.

**Comment by davesteele** [comment]
Not really. It is now build for GNOME 3 only.

I've seen problems like that come from dependencies defined in setup.py before, but I see nothing like that in the current file. Could there be a dependency in the spec file?

**Comment by davesteele** [comment]
Here's a thought.

For Mint, the script failed on a stock install due to missing 'introspection data' for the GNOME Keyring. This was fixed by adding a dependency on "gir1.2-secret-1". (I know - not exactly intuitive)

Perhaps there is an analogous missing 'python-gi' sub-dependency for GTK in Fedora.

This is the current Debian Depends line:

Depends: ${misc:Depends}, python2.7, python-gi, libgtk-3-bin (>=3.10),
         gir1.2-secret-1

**Comment by davesteele** [comment]
@scop reports in #11 that the libwnck3 package resolves this.

**Comment by davesteele** [comment]
[fixed](https://bugzilla.redhat.com/show_bug.cgi?id=1268672)
